CUDA_VISIBLE_DEVICES=0 python main.py --test 5 --seed 28 &
CUDA_VISIBLE_DEVICES=1 python main.py --test 5 --seed 53 &
CUDA_VISIBLE_DEVICES=2 python main.py --test 5 --seed 66 &
CUDA_VISIBLE_DEVICES=3 python main.py --test 5 --seed 837 &
CUDA_VISIBLE_DEVICES=4 python main.py --test 5 --seed 1999 &
CUDA_VISIBLE_DEVICES=5 python main.py --test 5 --seed 9353 &
CUDA_VISIBLE_DEVICES=6 python main.py --test 5 --seed 2 &
CUDA_VISIBLE_DEVICES=7 python main.py --test 5 --seed 8 &
# CUDA_VISIBLE_DEVICES=5 python main.py --test 5 &
# CUDA_VISIBLE_DEVICES=6 python main.py --test 5 &
# CUDA_VISIBLE_DEVICES=7 python main.py --test 5 &